export const MOCK_TEACHERS = [
  {
    powerschool_teacher_id: 'T1001',
    display_name: 'Aroon Srisuk',
    email: 'aroon.srisuk@nis.ac.th',
    photo_url: null,
    room: '204',
  },
  {
    powerschool_teacher_id: 'T1002',
    display_name: 'Maya Chen',
    email: 'maya.chen@nis.ac.th',
    photo_url: null,
    room: '118',
  },
  {
    powerschool_teacher_id: 'T1003',
    display_name: 'Daniel Okonkwo',
    email: 'daniel.okonkwo@nis.ac.th',
    photo_url: null,
    room: '310',
  },
  {
    powerschool_teacher_id: 'T1004',
    display_name: 'Priya Nair',
    email: 'priya.nair@nis.ac.th',
    photo_url: null,
    room: '112',
  },
  {
    powerschool_teacher_id: 'T1005',
    display_name: 'Luca Moretti',
    email: 'luca.moretti@nis.ac.th',
    photo_url: null,
    room: 'Gym',
  },
  {
    powerschool_teacher_id: 'T1006',
    display_name: 'Hanae Fujita',
    email: 'hanae.fujita@nis.ac.th',
    photo_url: null,
    room: '221',
  },
  {
    powerschool_teacher_id: 'T1007',
    display_name: 'Samuel Brooks',
    email: 'samuel.brooks@nis.ac.th',
    photo_url: null,
    room: '205',
  },
  {
    powerschool_teacher_id: 'T1008',
    display_name: 'Chanya Wattana',
    email: 'chanya.wattana@nis.ac.th',
    photo_url: null,
    room: '109',
  },
];
